### ISSUE TITLE
Unable to get sandbox started

### ISSUE THREAD

**Issue by dennisgyor** [stove-labs/granary#1]
Hello,

Following intructions and the build works okay but when I try to run the make start command, I get the following error:

Makefile:11: warning: overriding recipe for target 'start'
Makefile:2: warning: ignoring old recipe for target 'start'
sh ./scripts//commands.sh start
sh: 0: Can't open ./scripts//commands.sh
make: *** [Makefile:11: start] Error 127

There was another issue I resolved by mounting /tmp as writeable. I tried going into the sandox sub directory and setting the commands.sh to be executable but its looking like there is a directory missing in the path:

sh: 0: Can't open ./scripts//commands.sh

Should it be ./scripts/sandboxnet/commands.sh ?

Anyways, Im not sure how to resolve. 

Docker version:
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:03:46 2017
 OS/Arch:      linux/amd64
 Experimental: false
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

Docker-compose version:
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

Ubuntu version:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

**Comment by maht0rz** [comment]
Hi, thanks for reporting the issue you’re having.

Did you run the following command before make start?

source ./env/tezos/sandboxnet.sh

It sets up an environment variable that helps make find the correct scripts to run your stack.

**Comment by maht0rz** [comment]
Hi, thanks for your feedback.

Are you running ‘make start’ in the same shell instance as you did ‘source ./env/...’?

What’s the output if you echo $NETWORK_TYPE from the makefile?

P.S: with every new tab/window in terminal you must source the environment again to load $NETWORK_TYPE into your current shell.

**Comment by dennisgyor** [comment]
Hello,

Yes I ran this in the same shell. What I will do next is completely remove the project and start from scratch with the newest version of docker and docker-compose and see where that gets me. Its just weird that the full path isnt being picked up in the start command. 

What version of docker/compose did you build this on?

**Comment by maht0rz** [comment]
The issue you're having is before the setup has anything to do with Docker, it seems like the environment variables from 'source ./env/....` are not available in your shell.

1. `source ./env/tezos/sandboxnet.sh`
2. `make start`

(open a new shell for the client - possbily)
1. `source ./env/tezos/sandboxnet.sh`
2. `make client`

**Comment by maht0rz** [comment]
@dennisgyor Have you managed to resolve the issue?
